### ISSUE TITLE
拖拽获取颜色的ProgressView的bug

### ISSUE THREAD

**Issue by tiankongzhishang** [zhaoName/ProgressView#1]
拖动那个圆形的球拖到colorProgress的正中心的时候会崩溃,
// 拖拽点坐标到圆心的距离
    CGFloat distance = fabs(sqrt(squareDis));
    
    // 拖拽点与圆心的连线 与水平方向夹角的余弦值
    CGFloat cosX = fabs(centerOfCircle.x - btnPoint.x)/distance;
这个时候会趋近到等于0,0作为分母会出事

**Comment by zhaoName** [comment]
嗯嗯 这确实是个bug，不过好难复现啊，我一次都没做到。。

可以这样处理一下 CGFloat distance = MAX(0.1, fabs(sqrt(squareDis)));
